-- GoldStandard / MiPaymentChoice payment processor audit log.
-- Captures every API call (auth, tokenize, BCP sale) with masked PCI data.
-- Single-tenant: this Supply Admin install is wired to a single GS merchant
-- account configured via env vars, so no org_id is tracked.

create table if not exists public.goldstandard_payment_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  merchant_key text,
  operation text not null,
  method text not null,
  url text not null,
  request_headers jsonb,
  request_body jsonb,
  response_status integer,
  response_headers jsonb,
  response_body jsonb,
  error_message text,
  duration_ms integer
);

create index if not exists goldstandard_payment_logs_created_at_idx
  on public.goldstandard_payment_logs(created_at desc);

create index if not exists goldstandard_payment_logs_operation_idx
  on public.goldstandard_payment_logs(operation, created_at desc);

alter table public.goldstandard_payment_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'goldstandard_payment_logs'
      and policyname = 'goldstandard_payment_logs_admin_read'
  ) then
    create policy goldstandard_payment_logs_admin_read
      on public.goldstandard_payment_logs
      for select
      using (
        exists (
          select 1
          from public.user_profiles up
          where up.id = auth.uid()
            and up.role = 'admin'
        )
      );
  end if;
end
$$;

comment on table public.goldstandard_payment_logs is
  'Audit log of all GoldStandard/MiPaymentChoice API requests. Card numbers and CVV are masked at the application layer before writing.';
